[package]
name = "intelplanetary"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linemux = "0.2.2"
tokio = { version= "1.8.0", features = ["full"]}
env_logger = "0.8.4"
log = "0.4.14"
